FROM rocker/r-ver:4.1

RUN apt-get update && apt-get install -y liblzma-dev libbz2-dev zlib1g libpng-dev libxml2-dev \
    gfortran-7 libglpk-dev libhdf5-dev libcurl4-openssl-dev img2pdf python3.8 python3-dev python3-pip

RUN Rscript -e "install.packages(c('argparse', 'stringr', 'hdf5r', 'Matrix'))"
